apiVersion: v1
kind: Service
metadata:
  name: orc-site-test
  labels:
    app: orc-site-test
spec:
  type: NodePort
  selector:
    app: orc-site-test
  ports:
  - name: "http"
    protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30178
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orc-site-test
  labels:
    app: orc-site-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orc-site-test
  strategy:
    type: RollingUpdate  # default
  template:
    metadata:
      name: orc-site-test
      labels:
        app: orc-site-test
    spec:
      restartPolicy: Always  # default
      nodeSelector:
        staging: worker
      containers:
      - name: orc-site-test
        image: gesiscss/orc-site:52538ffd
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
        - name: DEPLOYMENT_ENV
          value:  "staging"
        resources:
          requests:
            cpu: "0.5"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
